"""add product featured status

Revision ID: 6ce0109251fa
Revises: b33b18f2c1be
Create Date: 2026-08-04 18:15:37.364795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce0109251fa'
down_revision: Union[str, Sequence[str], None] = 'b33b18f2c1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "products",
        sa.Column(
            "is_featured",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
            comment="Indica si el producto aparece como destacado.",
        ),
    )

    op.alter_column(
        "products",
        "is_featured",
        server_default=None,
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_featured')
    # ### end Alembic commands ###
