"""create catalog tables

Revision ID: b33b18f2c1be
Revises: 
Create Date: 2026-08-03 17:23:44.333684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33b18f2c1be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre de la marca.'),
    sa.Column('slug', sa.String(length=150), nullable=False, comment='Slug utilizado en la URL.'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='URL del logotipo de la marca.'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('name', name=op.f('uq_brands_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_brands_slug'))
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre de la categoría.'),
    sa.Column('slug', sa.String(length=150), nullable=False, comment='Slug utilizado en la URL.'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='Imagen representativa de la categoría.'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('products',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre comercial del producto.'),
    sa.Column('slug', sa.String(length=150), nullable=False, comment='Slug utilizado en la URL.'),
    sa.Column('brand_id', sa.BigInteger(), nullable=False, comment='Marca del producto.'),
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='Categoría del producto.'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Precio de referencia para comparar con el precio actual.'),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio actual de venta.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('compare_at_price IS NULL OR compare_at_price > current_price', name=op.f('ck_products_compare_at_price')),
    sa.CheckConstraint('current_price > 0', name=op.f('ck_products_current_price_positive')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    op.create_index('ix_products_brand_id', 'products', ['brand_id'], unique=False)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_name', table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_products_brand_id', table_name='products')
    op.drop_table('products')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
