#Meta
APP_MOVIL_SOLUCIONES_INTELIGENTES_META = {
    "titulo": "App Móvil Soluciones Inteligentes",
    "descripcion": "Aplicación móvil de Soluciones Inteligentes desarrollada con Kotlin y Android Studio que centraliza contenido de fitness, alimentación y salud, con herramientas para mejorar el entrenamiento y hábitos saludables."
}

#Sliders content
VERTICAL_SLIDER1_CONTENT = {
    "images": [
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_ad001.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_ad002.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_ad003.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_ad004.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_ad005.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_articulos.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_articulos_selector.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_articulos_selector2.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_articulos_selector3.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_articulos_selector4.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_articulos_selector5.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_articulos_selector6.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_articulos_contenido.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_articulos_contenido2.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_articulos_contenido3.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_ponte_en_forma_selector.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_ponte_en_forma_selector2.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_ponte_en_forma_contenido.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_ponte_en_forma_contenido2.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_ponte_en_forma_contenido3.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_ponte_en_forma_contenido4.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_ponte_en_forma_contenido5.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_ponte_en_forma_contenido6.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_recetas_de_cocina_selector.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_recetas_de_cocina_contenido.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_recetas_de_cocina_contenido2.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_si_recetas_de_cocina_contenido3.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_tiempo.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_tiempo_cronometro.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_tiempo_cronometro2.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_tiempo_temporizador.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_calculadora_IMC.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_calculadora_IMC2.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_calculadora_IMC3.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_tiempo_tabata_timer.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_tiempo_tabata_timer2.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_tiempo_tabata_timer3.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_tiempo_tabata_timer4.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_tiempo_tabata_timer5.webp"},
        {"url": "/static/img/proyectos/app_movil_soluciones_inteligentes/app_soluciones_inteligentes_tiempo_tabata_timer6.webp"},
    ],  

    "config": {
        "loop": "true"
    }
}

#Carrusel content
CARRUSEL_CONTENT = [
    {"id": "ekd9sq3XSJE", "alt": "app movil soluciones inteligentes",
     "url": "https://img.youtube.com/vi/ekd9sq3XSJE/hqdefault.jpg"},
     {"id": "08mukA4GgxE", "alt": "app móvil artículos soluciones inteligentes",
     "url": "https://img.youtube.com/vi/08mukA4GgxE/hqdefault.jpg"},
     {"id": "qTrcCEGLiEQ", "alt": "app móvil artículos ponte en forma conexión oculta",
     "url": "https://img.youtube.com/vi/qTrcCEGLiEQ/hqdefault.jpg"},
     {"id": "5K2sRAhwfKU", "alt": "app móvil artículos ponte en forma creatina",
     "url": "https://img.youtube.com/vi/5K2sRAhwfKU/hqdefault.jpg"},
     {"id": "_WN_2CydUHU", "alt": "app móvil enlace recetas de cocina",
     "url": "https://img.youtube.com/vi/_WN_2CydUHU/hqdefault.jpg"},
     {"id": "mPJWiMP3gZE", "alt": "app móvil enlace soluciones inteligentes",
     "url": "https://img.youtube.com/vi/mPJWiMP3gZE/hqdefault.jpg"},
     {"id": "G2sz6Rv5Bvc", "alt": "app móvil ponte en forma ciencia calentamiento",
     "url": "https://img.youtube.com/vi/G2sz6Rv5Bvc/hqdefault.jpg"},
     {"id": "pdtiErWhLqw", "alt": "app móvil recetas de cocina artículo azúcar",
     "url": "https://img.youtube.com/vi/pdtiErWhLqw/hqdefault.jpg"},
     {"id": "sXOfCFsxE0U", "alt": "app móvil recetas de cocina artículo higo",
     "url": "https://img.youtube.com/vi/sXOfCFsxE0U/hqdefault.jpg"},
     {"id": "2B7VM7V73Iw", "alt": "app móvil recetas de cocina barras de amaranto",
     "url": "https://img.youtube.com/vi/2B7VM7V73Iw/hqdefault.jpg"},
     {"id": "6IRimq_9XX8", "alt": "app móvil recetas de cocina croquetas de atún",
     "url": "https://img.youtube.com/vi/6IRimq_9XX8/hqdefault.jpg"},
     {"id": "4LVIB2Gaf_k", "alt": "app móvil recetas de cocina pan de maíz",
     "url": "https://img.youtube.com/vi/4LVIB2Gaf_k/hqdefault.jpg"},
     {"id": "zSywxSSe9cw", "alt": "app móvil recetas de cocina pan integral",
     "url": "https://img.youtube.com/vi/zSywxSSe9cw/hqdefault.jpg"},
     {"id": "W-6mf4cqef8", "alt": "app móvil soluciones inteligentes tiempo",
     "url": "https://img.youtube.com/vi/W-6mf4cqef8/hqdefault.jpg"},
     {"id": "OtMlsqt7_v4", "alt": "app móvil soluciones inteligentes cronometro",
     "url": "https://img.youtube.com/vi/OtMlsqt7_v4/hqdefault.jpg"},
     {"id": "TmfHAFqGabU", "alt": "app móvil soluciones inteligentes temporizador",
     "url": "https://img.youtube.com/vi/TmfHAFqGabU/hqdefault.jpg"},
     {"id": "Ov8R_UMG6Pk", "alt": "app móvil soluciones inteligentes tabata timer",
     "url": "https://img.youtube.com/vi/Ov8R_UMG6Pk/hqdefault.jpg"},
     {"id": "vhfhRxqLKLw", "alt": "app móvil soluciones inteligentes calculadora IMC",
     "url": "https://img.youtube.com/vi/vhfhRxqLKLw/hqdefault.jpg"}
]
